INTERACTIVE_KEY="ad1dff3fe37873f609b595"
INTERACTIVE_SECRET="Vxbr585@DS"
TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJKUEtTNF9BRDFERkYzRkUzNzg3M0Y2MDlCNTk1IiwicHVibGljS2V5IjoiYWQxZGZmM2ZlMzc4NzNmNjA5YjU5NSIsImlzSW50ZXJhY3RpdmUiOnRydWUsImlhdCI6MTcxNDYyODgwNCwiZXhwIjoxNzE0NzE1MjA0fQ.PJPKccww40RR9VoznSNziFZwGP2GKwo2il8ZLCE-dJM"
USERID="JPKS4"
DEMO_USERID="DELOPT"
DEMO_INTERACTIVE_KEY="7fcfb9db39a859fd798598"
DEMO_INTERACTIVE_SECRET="Orqq287#@m"
~                                                                                                                                                                
~                                    
